modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "yte"
version = "1.0.2-beta.1"
displayName = "Yunzhu Transit Extension"
authors = "xfunny\nMrNTKey\nQBYQ"
description = "äº‘ç«¹äº¤é?š\näº‘ç­‘å·¥åŠäº¤é?šæ‹“å±?"
logoFile = "icon.png"

[[dependencies.yte]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yte]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.yte]]
modId = "mtr"
mandatory = true
versionRange = "[4.0.0-beta.16,4.1)"
ordering = "AFTER"
side = "BOTH"
